// multitext must be before string
import './string'
import './select'
import './multitext'
import './number'
import './integer'
import './array'
import './boolean'
import './object'
import './multiple'
import './upload'
import './theme'
