// multitext must be before string
import './multitext'
import './string'
import './array_string'
import './array'
import './boolean'
import './object'
import './multiple'
import './upload'
import './theme'
