module.exports = {
    type: "object",
    description: "Task meta-data.",
    properties: {
        id: {
            type: "string",
            description:
                "Unique identifier for the task; we generally use the path in the SVN.",
            title: "id"
        },
        license: {
            type: "string",
            enum: ["CC-BY-SA", "CC-BY-NC"]
        },
        authors: {
            type: "array",
            items: {
                type: "string"
            }
        },
        language: {
            type: "string",
            description:
                'Language for the task. If you want to have this task in multiple languages, copy the "index.html" file generated by this editor to another file "index_en.html" (for instance), and edit it manually.',
            enum: ["fr", "en", "de"]
        },
        version: {
            type: "string",
            title: "version"
        },
        baseUrl: {
            type: "string",
            title: "baseUrl"
        }
    },
    required: ["id", "authors", "language"],
    generator: [
        {
            output: {
                inject: {
                    template: "index.html",
                    selector: "$json"
                }
            }
        }
    ]
};
